backend:
  name: git-gateway
  branch: main
media_folder: "static/images"
public_folder: "/images"
collections:
  - name: "dharma"
    label: "ဓမ္မ"
    folder: "content/dharma"
    create: true
    nested:
      depth: 2
      summary: "{{title}}"
    fields:
      - { label: "ခေါင်းစဉ်", name: "title", widget: "string" }
      - { label: "အကြောင်းအရာ", name: "body", widget: "markdown" }
      - { label: "အမျိုးအစား", name: "category", widget: "select", options: ["ပရိတ်", "ပဌာန်း", "မေတ္တာပို့"] }
  - name: "fortune"
    label: "ဗေဒင်"
    folder: "content/fortune"
    create: true
    nested:
      depth: 2
      summary: "{{title}}"
    fields:
      - { label: "ခေါင်းစဉ်", name: "title", widget: "string" }
      - { label: "အကြောင်းအရာ", name: "body", widget: "markdown" }
      - { label: "အမျိုးအစား", name: "category", widget: "select", options: ["ဇာတာစစ်မယ်", "အသားလှုပ်နမိတ်အဟော", "အဆောင်ယတြာ", "ဂဏန်းဗေဒင်", "အိမ်မက်ဟောစာတမ်း", "မှဲ့ဟောစာတမ်း"] }
  - name: "health"
    label: "ကျန်းမာရေး"
    folder: "content/health"
    create: true
    nested:
      depth: 2
      summary: "{{title}}"
    fields:
      - { label: "ခေါင်းစဉ်", name: "title", widget: "string" }
      - { label: "အကြောင်းအရာ", name: "body", widget: "markdown" }
      - { label: "အမျိုးအစား", name: "category", widget: "select", options: ["အိမ်တွင်းကုထုံး", "ရောဂါလက္ခဏာ", "ရိုးရာ"] }
  - name: "jataka"
    label: "ဇာတ်ကတ္ထဳ"
    folder: "content/jataka"
    create: true
    nested:
      depth: 2
      summary: "{{title}}"
    fields:
      - { label: "ခေါင်းစဉ်", name: "title", widget: "string" }
      - { label: "အကြောင်းအရာ", name: "body", widget: "markdown" }
      - { label: "အမျိုးအစား", name: "category", widget: "select", options: ["အခန်း-၁", "အခန်း-၂", "အခန်း-၃"] }