backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/uploads"

collections:
  - name: "dharma"
    label: "တရားတော်များ"
    folder: "content/dharma"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
  - name: "karma"
    label: "ကံကြမ္မာရေးရာ"
    folder: "content/karma"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
  - name: "health"
    label: "ကျန်းမာရေးရာ"
    folder: "content/health"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
  - name: "jataka"
    label: "ဇာတ်နိပါတ်တော်"
    folder: "content/jataka"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "ခေါင်းစဉ်", name: "title", widget: "string"}
      - {label: "အကြောင်းအရာ", name: "body", widget: "markdown"}