backend:
  name: git-gateway
  branch: main
media_folder: "static/images"
public_folder: "/images"
collections:
  - name: "dharma"
    label: "Dharma"
    folder: "content/dharma"
    create: true
    nested:
      depth: 2
      summary: "{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Category", name: "category", widget: "select", options: ["ပရိတ်", "ပဌာန်း", "မေတ္တာပို့"] }
  - name: "fortune"
    label: "Fortune"
    folder: "content/fortune"
    create: true
    nested:
      depth: 2
      summary: "{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Category", name: "category", widget: "select", options: ["ဇာတာစစ်မယ်", "အသားလှုပ်နမိတ်အဟော", "အဆောင်ယတြာ", "ဂဏန်းဗေဒင်", "အိမ်မက်ဟောစာတမ်း", "မှဲ့ဟောစာတမ်း"] }
  - name: "health"
    label: "Health"
    folder: "content/health"
    create: true
    nested:
      depth: 2
      summary: "{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Category", name: "category", widget: "select", options: ["home-remedies", "symptoms", "traditional"] }
  - name: "jataka"
    label: "Jataka"
    folder: "content/jataka"
    create: true
    nested:
      depth: 2
      summary: "{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Category", name: "category", widget: "select", options: ["chapter-1", "chapter-2", "chapter-3"] }